name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: test
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  pull_request:
    paths:
      # trigger release workflow if this file change
      - '.github/workflows/release.yml'

jobs:
  tagname:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.tag }}
    steps:
      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/tags/}" >> $GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "TAG_NAME=debug" >> $GITHUB_ENV
      - id: tag
        run: echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

  build-and-upload:
    runs-on: ubuntu-latest
    needs: tagname
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - name: Build shadowJar with Gradle
        run: gradle shadowJar
      - name: Upload shadowJar
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/libs/*-all.jar
          retention-days: 1

  publish-jar:
    if: github.event_name != 'pull_request'
    needs:
      - build-and-upload
      - tagname
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: ${{ needs.tagname.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Download shadowJar
        uses: actions/download-artifact@v4
      - name: Create Github Release
        run: |
          gh release create $TAG_NAME --title "$TAG_NAME" --target $GITHUB_SHA build/*
